#include <iostream>
#include <cmath>
#include <string>

using namespace std;

void projecteuler1();
void projecteuler2();
void projecteuler3();
void projecteuler4();

int main() {
	projecteuler4();
	return 0;
}

/*
projecteuler.net Problem 1
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.
*/
void projecteuler1(){
	int sum = 0;
	int num = 0;
	for (int i = 0; i < 1000; i++) {
		if (i % 3 == 0 || i% 5 == 0) {
			num = i;
			sum += num;
			}
	}
	cout << "The sum of all the multiples of 3 or 5 below 1000 is " << sum << endl;
}

/*
projecteuler.net Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
void projecteuler2() {
	//generate the fibonnacci sequence
	unsigned int sum = 0;
	int storage; //to store the previous number temporarily
	int prevnum = 0;
	int fibonacci = 1;
	bool fourmil = false;
	while (fourmil == false) {
		if (fibonacci < 4000000) {
			storage = fibonacci;
			fibonacci += prevnum;
			prevnum = storage;
			if (fibonacci % 2 == 0) {
				sum += fibonacci;
			}
		}
		else {
			fourmil = true;
		}
		
	}
	cout << "The sum of all even terms in the Fibonacci sequence whose values do not exceed four million are: " << sum << endl;
}
/*
projecteuler.net Problem 3
What is the largest prime factor of the number 600,851,475,143 ?
*/
void projecteuler3() {

	const long long number = 600851475143;
	long long tempnum = number;
	long long largestprime = 0;

	int counter = 2;
	while (counter * counter <= tempnum) {
		if (tempnum % counter == 0) {
			tempnum = tempnum / counter;
			largestprime = counter;
		}
		else {
			counter = (counter == 2) ? 3 : counter + 2;
		}
	}
	if (tempnum > largestprime) { // the remainder is a prime number
		largestprime = tempnum;
	}
	cout << "The largest prime factor of 600,851,475,143 is " << largestprime << endl;
}